// Generative UI — the emit_ui tool.
// The frontend parses a {type:"ui"} SSE frame off the chat stream and renders only
// design-system components validated against genui-catalog.schema.json (GENERATED from the
// frontend's zod catalog — copy from DoorKnockerPlus_Frontend `npm run genui:catalog`, never
// hand-edit). This tool lets the agent render those blocks: it validates the frame server-side
// (ajv), then emits it into a job — the gateway forwards the buffered frame onto the chat SSE.
// The tool's RETURN value is a tiny ack so the (large) UI payload never re-enters the model's
// context.
import { z } from "zod";
import { asText, loosenToolSchema, payload, roleAreaDenial, writeNorm } from "./tool-helpers.mjs";
import { callApi } from "./helpers.mjs";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import Ajv from "ajv/dist/2020.js";
import { createJob, jobEmit, jobComplete } from "./jobs.mjs";

const __dir = dirname(fileURLToPath(import.meta.url));
// One artifact, generated by the frontend's `npm run genui:catalog` and copied here verbatim: the
// component catalog AND the app's real route patterns (see checkLinks).
export const CATALOG_ARTIFACT = JSON.parse(readFileSync(join(__dir, "genui-catalog.schema.json"), "utf8"));
const CATALOG = CATALOG_ARTIFACT.catalog;
const COMPONENT_SCHEMAS = CATALOG.components;
const COMPONENT_TYPES = Object.keys(COMPONENT_SCHEMAS);

// Renderer caps (must match the frontend Surface.tsx).
const MAX_COMPONENTS = 50;
const MAX_DEPTH = 12;
// Components whose `children` arrays hold child component IDs (for depth/cycle checks).
const CONTAINER_KEYS = { Row: "children", Column: "children", Card: "children" };

const ajv = new Ajv({ allErrors: true, strict: false });
const validators = {};
for (const [name, schema] of Object.entries(COMPONENT_SCHEMAS)) validators[name] = ajv.compile(schema);

// ── Validation parity with the frontend (bug-bash 2026-07-24) ─────────────────
// The frontend's zod catalog STRIPS unknown props (no .strict() anywhere) — but the generated
// JSON schema says additionalProperties:false, so ajv REJECTED frames the frontend would have
// rendered fine. Worse, for union-heavy components (TemplateProposal: 38 strict objects, 6
// anyOf) errors[0] was a bare "must NOT have additional properties" with the property name
// dropped, and the model looped retrying blind. Two fixes:
//   1. strip-parity: delete exactly the offending additional properties (ajv names them in
//      params.additionalProperty) and re-validate — mirroring what zod does on render;
//   2. when a frame still fails, report the DEEPEST real errors with property names and
//      allowed values, skipping anyOf/discriminator noise.
// Pick the union branch a value is aimed at: first by a `const` discriminator property
// (elements carry type:"shape"|"text"|…), else by required-key presence (fills: {color} vs
// {gradient}). Null when nothing matches — then we don't strip (validation reports normally).
function pickBranch(branches, value) {
  if (value == null || typeof value !== "object") return null;
  for (const b of branches) {
    const disc = Object.entries(b.properties ?? {}).find(([, s]) => s && s.const !== undefined);
    if (disc && value[disc[0]] === disc[1].const) return b;
  }
  for (const b of branches) {
    const req = b.required ?? [];
    if (req.length && req.every((k) => k in value)) return b;
  }
  return null;
}
// Schema-aware unknown-property strip (zod-parity: the frontend silently drops extras).
// IMPORTANT: naive stripping from ajv's additionalProperties errors is WRONG for unions — the
// non-matching branches flag every branch-specific prop as "additional" and blind deletion
// destroys valid elements. This walker descends the schema, resolves each union to ITS branch,
// and strips only genuinely-unknown keys. Mutates `value` in place.
function stripUnknown(schema, value) {
  if (!schema || value == null || typeof value !== "object") return;
  const branches = schema.oneOf ?? schema.anyOf;
  if (branches) {
    const b = pickBranch(branches, value);
    if (b) stripUnknown(b, value);
    return;
  }
  if (Array.isArray(value)) {
    if (schema.items) for (const item of value) stripUnknown(schema.items, item);
    return;
  }
  const props = schema.properties;
  if (props) {
    if (schema.additionalProperties === false) {
      for (const k of Object.keys(value)) if (!(k in props)) delete value[k];
    }
    for (const [k, sub] of Object.entries(props)) if (k in value) stripUnknown(sub, value[k]);
  }
}
function formatErrors(errors) {
  const real = (errors ?? []).filter((e) =>
    e.keyword !== "anyOf" && e.keyword !== "oneOf" &&
    !(e.keyword === "const" && /\/type$/.test(e.instancePath)) &&
    !(e.keyword === "enum" && /\/type$/.test(e.instancePath)));
  const pool = real.length ? real : (errors ?? []);
  // Union noise: several branches report "required" at the same path — fold them into one line.
  const requiredByPath = new Map();
  const rest = [];
  for (const e of pool) {
    if (e.keyword === "required" && e.params?.missingProperty) {
      const set = requiredByPath.get(e.instancePath) ?? new Set();
      set.add(e.params.missingProperty);
      requiredByPath.set(e.instancePath, set);
    } else {
      rest.push(e);
    }
  }
  const lines = [];
  for (const [path, propsSet] of requiredByPath) {
    const names = [...propsSet];
    lines.push(`${path || "(root)"} is missing ${names.length > 1 ? `one of: ${names.join(" | ")}` : `required property "${names[0]}"`}`);
  }
  for (const e of rest) {
    let msg = `${e.instancePath || "(root)"} ${e.message}`;
    if (e.params?.additionalProperty) msg += ` ("${e.params.additionalProperty}" is not a valid property here — remove it)`;
    if (e.params?.allowedValues) msg += ` (allowed: ${e.params.allowedValues.join(", ")})`;
    lines.push(msg);
  }
  return lines
    .sort((a, b) => b.indexOf(" ") - a.indexOf(" ")) // deepest paths first (longer pointer prefix)
    .slice(0, 3)
    .join("; ") || "invalid props";
}
// Validate one component's props with frontend strip-parity.
// Returns { ok:true, props } (possibly stripped) or { ok:false, error }.
function validateComponentProps(type, props) {
  const validate = validators[type];
  if (validate(props)) return { ok: true, props };
  const work = JSON.parse(JSON.stringify(props));
  stripUnknown(COMPONENT_SCHEMAS[type], work);
  if (validate(work)) return { ok: true, props: work };
  return { ok: false, error: formatErrors(validate.errors) };
}

// ── the model must not choose a singleton card's surface_id (2026-08-04) ──────
// REPORTED LIVE: the audience builder appeared twice in one conversation. The trace showed two
// create_campaign calls with IDENTICAL arguments producing two campaigns, and an emit_ui for each:
//   turn A   surface_id "audience-location-zone"          campaign_id 951d214a…
//   turn B   surface_id "audience_builder_location_zone"  campaign_id 97e650fa…
// The duplicate campaign is a separate defect. What belongs here is the second half: the model chose
// the surface_id both times, from memory of what it had used before, and PARAPHRASED itself. Since
// upsertSurface (frontend) and the consumed-surface lifecycle (D4, gateway) both key on surface_id, a
// paraphrase is a brand-new surface — so the same logical card renders twice instead of replacing
// itself in place. That is true even for a single campaign: any revise can duplicate a card this way.
//
// The fix is to remove the discretion. These components are SINGLETONS: exactly one audience builder
// exists per campaign, one uploader per referral gallery, one switch per organisation. Their identity
// is fully determined by (component type + the thing they act on), so the id is derived here and the
// model's is ignored. Two emits for the same target now collide by construction, which is what
// "re-emit to revise in place" was always supposed to mean.
//
// Deliberately NOT applied to the generic blocks (Text, DataTable, StatCards, CampaignList…). A
// campaign list and a chart are genuinely different surfaces even in the same conversation, and the
// model choosing ids there is correct — there is nothing intrinsic to derive from.
const SINGLETON_SURFACES = {
  AudienceBuilder: (p) => p?.campaign_id,
  LaunchButton: (p) => p?.campaign_id,
  VerifyAddressesButton: (p) => p?.campaign_id,
  AddressListUploader: (p) => p?.campaign_id,
  OrgSwitchButton: (p) => p?.organization_id,
  // A referral gallery is per referral; the org logo/gallery targets are one apiece.
  ImageUploader: (p) => (p?.referral_id ? `${p.target}:${p.referral_id}` : p?.target),
  // A proposal for a campaign replaces in place. A LIBRARY proposal has no target id, so it keeps the
  // model's id: the user may well be shown several candidate designs side by side.
  // An EDIT is per bundle-side — a revised edit of the same side must replace the earlier card, or the
  // user is left choosing between two versions of one change.
  TemplateProposal: (p) => (p?.bundle_id && p?.side ? `${p.bundle_id}:${p.side}` : p?.campaign_id),
};

/**
 * The surface_id a frame must use, or null to keep the model's.
 *
 * Applies when the frame contains EXACTLY ONE singleton component — the shape these cards always take.
 * A frame mixing two of them has no single identity, so it keeps the model's id rather than being
 * forced into one of them arbitrarily.
 */
export function derivedSurfaceId(components) {
  const hits = [];
  for (const n of components ?? []) {
    const keyOf = SINGLETON_SURFACES[n?.type];
    if (!keyOf) continue;
    const target = keyOf(n.props);
    if (typeof target === "string" && target.trim()) hits.push(`${n.type}:${target.trim()}`);
  }
  return hits.length === 1 ? hits[0] : null;
}

// ── opacity is a PERCENTAGE, and the model writes CSS fractions (2026-08-03) ───
// REPORTED LIVE, twice: asked to put a semi-transparent band behind text so it would read against the
// photos, the agent said it had ("every text element now sits on a 55%-opacity dark band") and the
// design looked unchanged. The trace showed it had done the job properly — a dark #1D1D20 rectangle
// before each text element, correct paint order, correct geometry — and written `opacity: 0.55`.
//
// The schema is `{minimum: 0, maximum: 100}`: a PERCENTAGE. So 0.55 validated, meaning 0.55%, and the
// generator emitted `opacity: 0.0055`. Three invisible bands. The model used the CSS 0-1 convention and
// nothing objected, because the wrong value sits comfortably inside the right range.
//
// This was never a false claim — the intent was exactly right and the units disagreed silently, which
// no amount of "verify what you assert" would have caught. It needs a check on the VALUE.
//
// NORMALISE rather than refuse. Every value in (0, 1] is meaningless as a percentage: 1% opacity is
// already invisible, so nobody has ever wanted 0.55%. Reading it as a fraction is unambiguous, and it
// is what the author meant. `opacity: 1` is treated as fully opaque for the same reason — 1% would make
// an element vanish, and 100 is the default anyway. Refusing instead would cost the user a turn to fix
// something we can already read correctly; the tool result names the correction so the model learns.
// THE SAME MISTAKE HAPPENS TO GRADIENT STOPS, and it reached production (trace 019fd190, 2026-08-05).
// Asked to bring the front's teal-to-orange gradient onto the back, the model wrote
//   stops: [{color:"#47BAD7", position:0}, {color:"#E36A00", position:1}]
// `position` is a PERCENTAGE too, so that is a gradient which finishes inside its first 1% — a flat
// orange panel, not the blend it described. Same silent failure as opacity: the wrong value sits
// comfortably inside the valid range.
//
// Reading them as fractions is unambiguous. A two-stop gradient at 0% and 1% is meaningless, and any
// stop list whose LARGEST position is <= 1 cannot be a percentage anyone intended — 0..1 is exactly
// how CSS colour stops are written elsewhere. Note the test is on the maximum across the whole list,
// not per stop, so a legitimate [0, 50, 100] is untouched even though its first stop is 0.
//
// AND IT HAS TO WALK EDIT OPS. The original version only looked at spec.front/back.elements, so once
// a proposal could carry `ops` instead, every element the agent ADDED to an existing design skipped
// the correction entirely. Found while reading the trace above, not by a test — which is why the
// tests below cover the ops path explicitly.
const OPACITY_HOSTS = ["front", "back"];

/** Fix one element's opacity in place; returns a description when it changed. */
function fixOpacity(el, where) {
  const o = el?.opacity;
  if (typeof o !== "number" || !Number.isFinite(o) || o <= 0 || o > 1) return null;
  // Rounded to 2dp: 0.55 * 100 is 55.00000000000001 in binary floating point, and that would ride
  // into the spec and out into the generated CSS. Two decimals is finer than any display can show.
  el.opacity = Math.round(o * 10000) / 100;
  return `${where} ${el.type ?? "element"} opacity: ${o} → ${el.opacity}`;
}

/** Fix a fill's gradient stop positions in place; returns a description when they changed. */
function fixFill(fill, where) {
  const stops = fill?.gradient?.stops;
  if (!Array.isArray(stops) || stops.length < 2) return null;
  const positions = stops.map((s) => s?.position).filter((p) => typeof p === "number" && Number.isFinite(p));
  if (positions.length !== stops.length) return null;      // a partly-positioned list is not ours to guess at
  const max = Math.max(...positions);
  if (max <= 0 || max > 1) return null;                    // 0-100 already, or nothing to scale
  const before = positions.join(",");
  stops.forEach((s) => { s.position = Math.round(s.position * 10000) / 100; });
  return `${where} gradient stops: ${before} → ${stops.map((s) => s.position).join(",")}`;
}

/** Walk anything element-shaped, wherever it lives. */
function fixElement(el, where, fixed) {
  const o = fixOpacity(el, where); if (o) fixed.push(o);
  const f = fixFill(el?.fill, where); if (f) fixed.push(f);
}

/**
 * Rewrite fractional opacities and gradient stop positions in place, for BOTH proposal shapes — a new
 * design's front/back elements and an edit's ops. Returns one label per correction, which the tool
 * result reports so the model does not describe the design using the number it sent.
 */
export function normalizeSpecOpacity(spec) {
  const fixed = [];
  if (!spec || typeof spec !== "object") return fixed;
  for (const side of OPACITY_HOSTS) {
    const s = spec[side];
    if (!s || typeof s !== "object") continue;
    const bg = fixFill(s.background, `${side} background`); if (bg) fixed.push(bg);
    if (!Array.isArray(s.elements)) continue;
    s.elements.forEach((el, i) => fixElement(el, `${side}[${i}]`, fixed));
  }
  if (Array.isArray(spec.ops)) {
    spec.ops.forEach((op, i) => {
      if (!op || typeof op !== "object") return;
      if (op.element) fixElement(op.element, `ops[${i}] add`, fixed);
      if (op.op === "set_background") {
        const f = fixFill(op.fill, `ops[${i}] set_background`); if (f) fixed.push(f);
      }
    });
  }
  return fixed;
}

// Normalize both accepted wire forms into { id, type, props }.
function normalizeEntry(entry) {
  if (!entry || typeof entry !== "object") return null;
  const id = entry.id;
  if (typeof id !== "string" || !id) return { error: "component entry missing string id" };
  if (entry.component && typeof entry.component === "object") {
    const keys = Object.keys(entry.component);
    if (keys.length !== 1) return { error: `component "${id}" must wrap exactly one type` };
    return { id, type: keys[0], props: entry.component[keys[0]] ?? {} };
  }
  if (typeof entry.componentType === "string") {
    return { id, type: entry.componentType, props: entry.properties ?? {} };
  }
  return { error: `component "${id}" has no component/componentType` };
}

// ── Links must be in-app paths that EXIST (2026-08-03) ────────────────────────
// REPORTED LIVE: at the final step of an address-list campaign the user asked to verify the addresses.
// The agent correctly said it could not do that itself and offered a button — built as a generic Button
// with `action: {type:"openUrl", url:"https://app.doorknockerplus.com/campaigns/<id>/addresses/verify"}`.
// The click opened a new tab on a dead page, at the step where the user was about to pay.
//
// The model invented the ENTIRE url — host included. This app is served from
// doorknocker.texasgrowthfactory.com (production) and door-knocker-plus-dev.vercel.app (development);
// `app.doorknockerplus.com` is not ours and does not exist. Neither real host is remotely guessable
// from the product name, which is the real lesson: the failure was not a wrong path, it was the agent
// COMPOSING an absolute url at all. It cannot know this app's hosts, so anything it builds is a guess
// that merely reads plausibly.
//
// TWO RULES, and they are different in kind:
//
// 1. openUrl is REFUSED outright in a Button action. Every absolute url the agent could legitimately
//    offer would have to come from a tool result, and no tool returns one that belongs behind a button:
//    `website_url` is the customer's own site, `logo_url` and gallery urls are images (which travel in
//    Image.url, untouched by this). So there is nothing to preserve, and refusing the whole action type
//    removes the class — invented hosts, invented paths, in-app screens torn out into a new tab, and any
//    look-alike link the model could be led into rendering.
//
//    An earlier attempt here tried to allow "genuine external" urls by checking the host against an
//    allowlist. That was wrong twice over: it would have let this very frame through (the invented host
//    matches no allowlist, so it read as external), and the allowlist itself was built from a domain the
//    model had hallucinated. Distinguishing a real external url from a fabricated one is not something
//    this layer can do; not needing to is better than doing it badly.
//
// 2. navigate / NavButton hrefs are checked against the app's REAL routes, generated from
//    src/routes/index.tsx by the frontend's `npm run genui:catalog` and carried in this artifact. Two
//    lists, answering different questions:
//      routes             — will this path resolve at all?
//      assistant_linkable — may the agent send the user HERE? /login and /pick-organization resolve, but
//                           the widget unmounts on them (AssistantMount), so the conversation would
//                           vanish.
//    A hand-written list was tried first and was wrong in both directions — it included `billing`,
//    `notifications` and singular `campaign`/`referral`/`template`, none of which are routes. Guessing
//    the app's shape is the mistake being caught here; it has no place in the catcher.
// ── the BACK has a reserved postal area, and the model was never told (2026-08-06) ────────────
// REPORTED BY QA: "the back side of the postcard is not created according to the user's request." The
// model designed the back freely because nothing told it not to, and generateHTML then masks the
// address block and the USPS barcode WHITE for print — so whatever it put there vanished. One reported
// design had SEVEN elements in that area.
//
// The usable area is much smaller than the card: on a 4x6 it is 132px of the 600px width, because the
// USPS barcode alone is 456px wide. That is not something a model can infer, and the card's overlap
// warning only fires after the design exists. Stating it up front is the fix; the warning stays as the
// backstop. Generated from the app's own zone config (artifact.postcard_zones) so it cannot drift.
const ZONES = CATALOG_ARTIFACT.postcard_zones ?? null;
const backZoneRule = () => {
  if (!ZONES) return "";
  const per = Object.entries(ZONES)
    .map(([size, z]) => `${size}: keep back elements within x 0-${z.back_art.width}, y 0-${z.back_art.height} (card is ${z.document.width}x${z.document.height})`)
    .join("; ");
  return "BACK SIDE — the right-hand strip of the back is reserved for the mailing address and the USPS barcode, and the print service MASKS IT WHITE. Anything you place there is destroyed, not moved. "
    + `Usable area per size — ${per}. `
    + "A full-bleed background on the back is fine (it is expected to be covered); TEXT, IMAGES and QR codes must sit inside the usable area or the user loses them. ";
};

const ROUTES = Array.isArray(CATALOG_ARTIFACT.routes) ? CATALOG_ARTIFACT.routes : null;
const LINKABLE = Array.isArray(CATALOG_ARTIFACT.assistant_linkable) ? CATALOG_ARTIFACT.assistant_linkable : null;

// Hoisted and built without template literals: the class contains `${`, which inside a template literal
// reads as the start of an interpolation.
const REGEX_SPECIALS = /[.*+?^${}()|[\]\\]/g;
/** A route pattern → matcher. `:param` is one segment; `:param?` is an optional one. */
function routeMatcher(pattern) {
  const parts = pattern.split("/").filter(Boolean).map((seg) => {
    if (seg.startsWith(":")) return seg.endsWith("?") ? "(?:/[^/]+)?" : "/[^/]+";
    return "/" + seg.replace(REGEX_SPECIALS, "\\$&");
  });
  // Trailing slash tolerated, case-insensitive: React Router matches that way by default.
  return new RegExp("^" + (parts.join("") || "/") + "/?$", "i");
}
const MATCHERS = ROUTES ? ROUTES.map((r) => routeMatcher(r)) : null;
const LINKABLE_MATCHERS = LINKABLE ? LINKABLE.map((r) => routeMatcher(r)) : null;
const matchesAny = (list, path) => !!list?.some((re) => re.test(path));

/** The path part of an in-app href, without query or hash. Null when it is not a bare path. */
export function pathOf(href) {
  const raw = String(href ?? "");
  if (!raw.startsWith("/")) return null;
  return raw.split("?")[0].split("#")[0];
}

const USE_INSTEAD = "For an ACTION, use the purpose-built component rather than a link: address verification → VerifyAddressesButton{campaign_id, campaign_name}; launching → LaunchButton{campaign_id, campaign_name}; attaching a CSV → AddressListUploader{campaign_id}; setting an audience → AudienceBuilder{campaign_id}; adding a photo or logo → ImageUploader{target}; switching organization → OrgSwitchButton. Each opens the real in-app flow where the user reviews and confirms.";

/**
 * Refusal text for any unusable link in the frame, else null.
 *
 * Route checking degrades OPEN when the artifact carries no `routes` (a service deployed before the
 * artifact was re-copied): it must never refuse links it simply cannot verify. The openUrl rule needs
 * no artifact and therefore always applies.
 */
export function checkLinks(components) {
  for (const n of components ?? []) {
    const action = n?.props?.action;

    if (action?.type === "openUrl") {
      return `component "${n.id}" uses action {type:"openUrl"}, which is not allowed: you composed that url, and the app's real addresses are not something you can know. ${USE_INSTEAD} To send the user to a screen, use NavButton{href} or action {type:"navigate", href:"/path"} with one of these in-app paths: ${(LINKABLE ?? []).slice(0, 14).join(", ")} — substituting a real id, from a tool result, for any :param.`;
    }

    const href = action?.type === "navigate" ? action.href : (n?.type === "NavButton" ? n.props?.href : null);
    const path = pathOf(href);
    if (path === null || !MATCHERS) continue; // not a judgeable path, or no oracle available

    if (!matchesAny(MATCHERS, path)) {
      return `component "${n.id}" links to "${path}", which is NOT a screen in this app — that path was composed rather than read from a tool result, so it will not open. ${USE_INSTEAD} The real screens are: ${(LINKABLE ?? []).slice(0, 14).join(", ")}. Substitute a real id for any :param.`;
    }
    if (LINKABLE_MATCHERS && !matchesAny(LINKABLE_MATCHERS, path)) {
      return `component "${n.id}" links to "${path}", which is a real page but NOT one to send the user to — you are not available there, so the conversation would disappear. Keep the user inside the app: ${(LINKABLE ?? []).slice(0, 14).join(", ")}.`;
    }
  }
  return null;
}


// Validate a full frame. Returns { ok:true, frame } or { ok:false, error }.
export function validateUiFrame(input) {
  if (!input || typeof input !== "object") return { ok: false, error: "frame must be an object" };
  const surface_id = input.surface_id;
  if (typeof surface_id !== "string" || !surface_id) return { ok: false, error: "surface_id (string) is required" };
  const root = input.root;
  if (typeof root !== "string" || !root) return { ok: false, error: "root (component id) is required" };
  const mode = input.mode ?? "replace";
  if (mode !== "replace") return { ok: false, error: `mode must be "replace" (patch is reserved)` };
  if (!Array.isArray(input.components) || input.components.length === 0) return { ok: false, error: "components must be a non-empty array" };
  if (input.components.length > MAX_COMPONENTS) return { ok: false, error: `too many components (${input.components.length} > ${MAX_COMPONENTS})` };

  const byId = new Map();
  const normalized = [];
  for (const entry of input.components) {
    const n = normalizeEntry(entry);
    if (!n || n.error) return { ok: false, error: n?.error ?? "invalid component entry" };
    if (byId.has(n.id)) return { ok: false, error: `duplicate component id "${n.id}"` };
    if (!COMPONENT_TYPES.includes(n.type)) return { ok: false, error: `unknown component type "${n.type}" (id "${n.id}")` };
    byId.set(n.id, n);
    normalized.push(n);
  }
  if (!byId.has(root)) return { ok: false, error: `root "${root}" is not among the components` };

  // Fractional opacities are corrected BEFORE prop validation, so the fixed value is what gets
  // validated, streamed, previewed and eventually baked into the saved HTML.
  const opacityFixes = [];
  for (const n of normalized) {
    if (n.type === "TemplateProposal") opacityFixes.push(...normalizeSpecOpacity(n.props));
  }

  // Per-component prop validation against the catalog schema (strip-parity with the frontend:
  // unknown extra properties are removed, not fatal — see validateComponentProps).
  for (const n of normalized) {
    const result = validateComponentProps(n.type, n.props);
    if (!result.ok) {
      return { ok: false, error: `${n.type} "${n.id}": ${result.error}` };
    }
    n.props = result.props;
  }

  // Runs AFTER prop validation so the props are normalized (and any unknown keys stripped) before the
  // action is inspected — otherwise a frame could be refused for a property that was about to be
  // dropped anyway.
  const linkError = checkLinks(normalized);
  if (linkError) return { ok: false, error: linkError };

  // A singleton card's id is derived from what it acts on, not from what the model typed (see
  // SINGLETON_SURFACES). Computed after prop validation so the identifying props are the normalized ones.
  const derivedId = derivedSurfaceId(normalized);
  const effectiveSurfaceId = derivedId ?? surface_id;

  // Referential integrity + depth + cycle check from root.
  const walk = (id, depth, path) => {
    if (depth > MAX_DEPTH) return `nesting exceeds ${MAX_DEPTH} at "${id}"`;
    if (path.has(id)) return `cycle detected at "${id}"`;
    const n = byId.get(id);
    if (!n) return `referenced component "${id}" does not exist`;
    const childKey = CONTAINER_KEYS[n.type];
    if (childKey) {
      const kids = n.props?.[childKey];
      if (Array.isArray(kids)) {
        const nextPath = new Set(path); nextPath.add(id);
        for (const k of kids) {
          const err = walk(k, depth + 1, nextPath);
          if (err) return err;
        }
      }
    }
    return null;
  };
  const err = walk(root, 1, new Set());
  if (err) return { ok: false, error: err };

  return {
    ok: true,
    // Reported back through the tool result so the model sees the correction rather than repeating it
    // next turn (and does not describe a band as 55% when it wrote 0.55).
    ...(opacityFixes.length ? { opacityFixes } : {}),
    ...(derivedId && derivedId !== surface_id ? { derivedSurfaceId: derivedId, requestedSurfaceId: surface_id } : {}),
    frame: {
      type: "ui",
      surface_id: effectiveSurfaceId,
      mode: "replace",
      root,
      // Always emit the canonical/preferred wire form {id, component:{Type:props}}
      // regardless of which form the model produced — the frontend prefers this one.
      components: normalized.map((n) => ({ id: n.id, component: { [n.type]: n.props } })),
      data_model: (input.data_model && typeof input.data_model === "object") ? input.data_model : {},
    },
  };
}

// ── a design proposal is a NEW design, never an edit (2026-08-04) ─────────────
// REPORTED LIVE. The user asked, over several turns, to "add picture on the back side of this template"
// and "add the tag line thank you for shopping". The agent fetched the bundle, then emitted a
// TemplateProposal with a completely INVENTED front — "BUILDING YOUR VISION" over a dark gradient — and
// described it as "both sides of the New Builds Construction design". The existing front was gone.
//
// CORRECTION (2026-08-05) — the original version of this comment gave two reasons and one was false:
//   * FALSE: "get_template_bundle returns no html by design (a design runs to 10k+ lines)".
//     getTemplateBundleById does return the artwork for both sides — data.front_template.html and
//     data.back_template.html — and the MCP was projecting it away by choice. Measured against a
//     44-row dump of the real templates table, a side is 8-16 KB and 35-56 LINES; the "10k+ lines"
//     figure was wrong by roughly 200x. (What IS true: 11 of those 44 rows exceed 1.4 MB because a
//     cropped image is inlined as base64 — handled by eliding the payload, see template-html.mjs.)
//   * TRUE: a TemplateProposal carrying front/back is a WHOLE design, so a back-only change could not
//     be expressed at all.
//
// Both halves are addressed now: get_template_side_html hands over the real html (with element ids),
// and a proposal may instead carry bundle_id + side + ops.
//
// The name check below therefore stays, with a different purpose. A proposal carrying front/back and
// named after a design that already exists is a REPLACEMENT dressed as an edit — the reported bug
// exactly — so it is refused and pointed at the edit path, rather than at the visual editor.
//
// No false positive on the normal revise loop: while a proposal is unsaved its name matches nothing in
// the library, so "request changes" → re-emit works exactly as before. Once it IS saved, a further
// change genuinely cannot be applied — so refusing then is right too.
//
// Scoped to LIBRARY proposals (no campaign_id). A campaign proposal is a campaign-specific copy and
// reusing the source design's name there is normal and harmless.
/**
 * Does `name` match a design already in the library? Pure, and exported, because ALL the judgement is
 * here: a bundle has no name of its own — the display name is a side template's description with a
 * trailing " Front"/" Back" token (the same rule bundleNameFromDescriptions and the frontend's
 * stripBundleSuffix apply), and comparison has to survive case and spacing differences.
 */
export function designNameClash(name, bundles) {
  const target = writeNorm(String(name ?? ""));
  if (!target) return null;
  for (const b of Array.isArray(bundles) ? bundles : []) {
    const desc = b?.front?.description ?? b?.back?.description
      ?? b?.front_template?.description ?? b?.back_template?.description ?? b?.name ?? "";
    const existing = writeNorm(String(desc).replace(/\s+(front|back)$/i, ""));
    if (existing && existing === target) return String(name).trim();
  }
  return null;
}

/**
 * A proposal is EITHER a new design (name + size + both sides) or an edit (bundle_id + side + ops).
 * Sending both is a model that has not decided which it is doing, and it must not be guessed at:
 * the ambiguity is exactly the reported bug — an "edit" that silently replaced the whole design.
 *
 * Checked on the RAW arguments, before validateUiFrame. The catalog schema is a union, and the
 * strip-parity walker resolves a union by required-key presence: a mixed payload matches the
 * new-design branch first, so `edit` would be quietly stripped and the proposal would go through as
 * a brand-new design. Refusing here is what stops that.
 */
export function mixedProposalModes(p) {
  if (!p || typeof p !== "object") return null;
  const isEdit = Array.isArray(p.ops) || typeof p.bundle_id === "string";
  const isNew = !!p.front || !!p.back;
  if (!isEdit || !isNew) return null;
  return {
    blocked: "proposal_is_new_or_edit_not_both",
    verified: false,
    retry: false,
    plain: "I got my wires crossed there — let me redo that.",
    note:
      "NOTHING was rendered. This proposal carries BOTH an edit (bundle_id/ops) and a whole design "
      + "(front/back). Those are different actions and I will not guess between them. To CHANGE a saved "
      + "design: send only bundle_id, side and ops — read the side first with get_template_side_html. To "
      + "propose a NEW design: send only name, postcard_size, front and back, and never name it after a "
      + "design that already exists.",
  };
}

async function savedDesignNameClash(proposalProps, userJwt) {
  if (!proposalProps || proposalProps.campaign_id) return null;
  const name = String(proposalProps.name ?? "").trim();
  if (!name) return null;
  const res = await callApi("getAllTemplatesBundlesV3", "GET", null, userJwt);
  if (!res || res.__error) return null; // cannot check → never block on a failed read
  return designNameClash(name, payload(res) ?? []);
}

export function registerGenUiTools(server, { userId, userJwt }) {
  server.registerTool("emit_ui", {
    description:
      "Render a rich UI block in the chat (design-system components) instead of plain prose. Use when a block genuinely beats text: campaign/referral/template lists, a targeting-zone map, metric tiles, readiness checklists, step guides, clickable choices. ALWAYS also answer briefly in text — the block supplements, never replaces. Prefer ONE domain component per surface. Re-call with the SAME surface_id to revise a block in place. Components (props): " +
      "CampaignList{title?,items[](max 20):{campaignId,name,status?,audienceCount?,spend?,sendDate?,size?}}, CampaignCard{campaignId,name,status?,audienceCount?,spend?,sendDate?,size?}, " +
      "ReferralList{title?,items[](max 20):{referralId,referrer,jobType?,jobValue?,status?}}, ReferralCard{referralId,referrer,jobType?,jobValue?,status?}, " +
      "PostcardPreview{bundleId,name?,size?} — REFERENCE ONLY: pass the bundle id, never HTML; the client fetches and renders the design itself. " +
      "TemplateList{title?,items[](max 20):{bundleId,name,size?,updatedAt?,usedInCampaigns?}}, " +
      "ZoneMap{title?,zoneId?,center?{lat,lng},points[](max 500):{lat,lng,kind?(home|business),status?(valid|opt_out|skipped),address?},counts?{valid?,optOut?,skipped?}} — live map; PREFER passing just zoneId (the client fetches the zone's addresses itself) over inline points. " +
      "DataTable{title?,columns[](max 8),rows[][](max 50 rows; string|number cells)}, StatCards{items[](max 8):{label,value,hint?,trend?(up|down|flat)}}, " +
      "Checklist{title,subtitle?,items[]:{label,status(pass|warn|fail),note?,fixPrompt?}}, GuideSteps{title,subtitle?,steps[]:{title,detail?,prompt,state(done|active|todo)}}, " +
      "ChoiceChips{choices[]:{label,prompt}}, NavButton{label,href(/path)}, " +
      "Text{text,variant?(title|subtitle|body|caption)}, Row{children[ids],gap?}, Column{children[ids],gap?}, Card{title?,children[ids]}, "
      + "NOTE on postcard designs: element `opacity` AND gradient stop `position` are both PERCENTAGES 0-100 (55 means 55%, and a two-colour gradient runs from position 0 to position 100), never 0-1 fractions — `opacity: 0.55` means 0.55% and renders invisible, and stops at 0 and 1 finish the blend inside the first 1%, giving a flat panel. Colours are plain 6-digit hex with no alpha. Elements paint in the order listed, so a band must come BEFORE the text it sits behind. "
      + backZoneRule()
      + "MERGE FIELDS: business_name, phone, website and the company logo are filled in from the organisation the moment the design is SAVED — use the `variable` element type for them and do NOT paste values you read in conversation. disclaimer_text and qr_url are filled in per campaign, so they stay as placeholders in a library design and that is correct. "
      + "CHANGING a design that already exists is a DIFFERENT shape of TemplateProposal: send `bundle_id`, `side` and `ops` and NOTHING else — no name, no front/back (those mean 'replace the whole design', which is never what 'edit this' means). First call get_template_side_html to read that side; it gives you each element's data-element-id, which is how an op names its target. ops: {op:'add',element,at?} | {op:'set_text',element_id,text,expect_text} | {op:'remove',element_id,expect_text?} | {op:'replace_image',element_id,source} | {op:'set_background',fill}. expect_text is the element's CURRENT words as you read them — if they don't match, nothing is applied and you're told what is really there. Everything you don't name is preserved exactly, and the side you don't name is never written at all. " +
      "Button{label,action,tone?(primary|neutral|ghost)}, Divider{}, Image{url(https),alt?}. " +
      "Button.action = {type:'send',prompt,display?} | {type:'navigate',href:'/path'}. NEVER {type:'openUrl'} — you cannot know this app's web addresses, so any url you write will be wrong; it is refused. " +
      "fixPrompt/GuideSteps.prompt/ChoiceChips.prompt/Button send prompt = the literal user message to receive when clicked. "
      + "hrefs are in-app paths only and must be REAL screens — /campaigns, /campaigns/{id}, /referrals, /referrals/{id}, /templates, /templates/{id}, /targeting/zones, /targeting/zones/{id}, /targeting/addresses, /targeting/exclusions, /analytics/overview, /analytics/campaign-performance, /settings, /team, /profile, /dashboard, /agency/overview. Any other path is refused: never assemble one, and take every {id} from a tool result. "
      + "For an ACTION, reach for the purpose-built component instead of a link: VerifyAddressesButton, LaunchButton, AddressListUploader, AudienceBuilder, ImageUploader, OrgSwitchButton. " +
      "Build every block from REAL tool data — never invent campaignIds, bundleIds, zoneIds, counts, or statuses. Where the data comes from: CampaignList/CampaignCard from list_campaigns, search_campaigns or get_campaign; StatCards from get_dashboard_analytics or get_summary_analytics; ZoneMap zoneId from get_targeting_summary or get_live_context; PostcardPreview/TemplateList from list_template_bundles or get_template_bundle; ReferralList from list_referrals or search_referrals; DataTable from any tabular read (analytics rows, billing history). " +
      "Don't over-render: a one-line factual answer stays prose. Reach for a block when there's a list, a comparison, something geographic, or a clear next step to click.",
    // loosenToolSchema (D7): the per-entry object is strict by default, so it publishes
    // additionalProperties:false — and Flowise rebuilds a strict zod schema from that, failing the
    // whole call when the model adds a redundant key to an entry (e.g. both `component` and a stray
    // `type`). The model then never sees this handler's actionable "has no component/componentType"
    // message and retries blind. Note this tool needs only the ADVERTISE half of D7, not the
    // execute-side declaredOnly the read/write registries use: nothing here forwards raw args
    // onward — normalizeEntry reads four known keys and validateUiFrame rebuilds the frame from
    // scratch, stripping unknown props against the generated catalog schema on the way.
    inputSchema: loosenToolSchema({
      surface_id: z.string().describe("Stable id. Re-emit the SAME id to replace/revise the block in place; a new id appends another block. For the interactive cards (AudienceBuilder, LaunchButton, VerifyAddressesButton, AddressListUploader, ImageUploader, OrgSwitchButton, and a campaign TemplateProposal) the id is DERIVED from what the card acts on and yours is ignored — one card per campaign/referral/organization, so re-emitting always replaces in place."),
      mode: z.enum(["replace"]).optional(),
      root: z.string().describe("id of the component to render as the root"),
      components: z.array(z.object({
        id: z.string(),
        component: z.record(z.any()).optional().describe('{"<TypeName>": { ...props }}'),
        componentType: z.string().optional(),
        properties: z.record(z.any()).optional(),
      })).describe("Flat array; children referenced by id"),
      data_model: z.record(z.any()).optional(),
    }),
    annotations: { readOnlyHint: false, destructiveHint: false },
  }, async (a) => {
    // Before validation: validateUiFrame STRIPS unknown keys, and for a mixed new-design/edit
    // payload that stripping would silently discard the edit half. See mixedProposalModes.
    for (const c of Array.isArray(a?.components) ? a.components : []) {
      const mixed = mixedProposalModes(c?.component?.TemplateProposal ?? (c?.componentType === "TemplateProposal" ? c?.properties : null));
      if (mixed) return asText(mixed);
    }
    const v = validateUiFrame(a);
    if (!v.ok) {
      return { isError: true, content: [{ type: "text", text: `emit_ui rejected: ${v.error}. Fix the payload and call emit_ui again.` }] };
    }
    // Designer surfaces are write paths in disguise: the proposal card's Approve button saves
    // to the design library (or the campaign) straight from the browser, bypassing the write
    // tools' role gates. Gate the surface itself: technicians never design; marketers may only
    // design FOR a campaign (library saves are template management, which their role excludes).
    const proposal = v.frame.components.find((c) => c.component?.TemplateProposal);
    if (proposal) {
      // You cannot edit a saved design — see savedDesignNameClash. Checked before the role gate so the
      // model gets the more specific answer.
      const clash = await savedDesignNameClash(proposal.component.TemplateProposal, userJwt);
      if (clash) {
        return asText({
          blocked: "cannot_edit_saved_design",
          verified: false,
          retry: false,
          plain: `That would have replaced "${clash}" with a brand-new design rather than changing it. Let me do it properly.`,
          note: `A proposal carrying front/back is a NEW design — sending one named after a design that already exists REPLACES it wholesale, which is not what "change this design" means. To actually edit "${clash}": call get_template_side_html with its bundle_id and the side you want to change, read what is there, then send a proposal carrying ONLY bundle_id, side and ops (targeting elements by their data-element-id). Everything you do not name is preserved exactly, and the other side is never touched. If you genuinely meant a NEW design inspired by this one, give it a DIFFERENT name and say plainly that it is a new design.`,
        });
      }
      const area = proposal.component.TemplateProposal?.campaign_id ? "campaigns" : "template_management";
      const denial = await roleAreaDenial(userJwt, area);
      if (denial) return asText(denial);
    }
    const job = createJob(userId, "emit_ui");
    jobEmit(job, v.frame);
    jobComplete(job, { surface_id: v.frame.surface_id });
    return asText({
      ok: true,
      surface_id: v.frame.surface_id,
      ui_job_id: job.id,
      rendered: a.components.length,
      // A silently-wrong unit is worth telling the model about: it wrote a CSS 0-1 fraction where the
      // spec takes a 0-100 percentage, which validated and rendered invisible. Corrected here, but it
      // must not describe the result using the number it sent.
      // The model should see that it does not own this id, so it stops trying to remember one.
      ...(v.derivedSurfaceId ? {
        surface_id_note: `This card's surface_id is derived from what it acts on, so yours ("${v.requestedSurfaceId}") was replaced with "${v.derivedSurfaceId}". Re-emitting for the same target always replaces the card in place — you never need to remember the id.`,
      } : {}),
      ...(v.opacityFixes?.length ? {
        corrected_opacity: v.opacityFixes,
        note: "`opacity` is a PERCENTAGE (0-100), not a 0-1 fraction. The values listed in corrected_opacity were rewritten for you — at the value you sent they would have been invisible. Use 55 (not 0.55) for a 55% band, and describe the design by the corrected values.",
      } : {}),
    });
  });
}
