"""
Fetches all Google Fonts via the Google Fonts API and generates a Supabase
SQL migration file that upserts every font into the `fonts` table.

Usage:
    python3 supabase/scripts/generate_fonts_migration.py

Output:
    supabase/migrations/<timestamp>_seed_google_fonts.sql
"""

import json
import os
import urllib.request
from datetime import datetime

# ── Config ───────────────────────────────────────────────────────────────────
# Uses google-webfonts-helper (no API key required, mirrors Google Fonts data)
GOOGLE_FONTS_URL = "https://gwfh.mranftl.com/api/fonts"

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MIGRATIONS_DIR = os.path.join(SCRIPT_DIR, "..", "migrations")
TIMESTAMP = datetime.utcnow().strftime("%Y%m%d%H%M%S")  # e.g. 20260330120000
MIGRATION_FILENAME = f"{TIMESTAMP}_seed_google_fonts.sql"
MIGRATION_PATH = os.path.join(MIGRATIONS_DIR, MIGRATION_FILENAME)

BATCH_SIZE = 100  # rows per INSERT statement


# ── Helpers ──────────────────────────────────────────────────────────────────

def pg_array(items: list[str]) -> str:
    """Convert a Python list to a PostgreSQL ARRAY literal."""
    escaped = [item.replace("'", "''") for item in items]
    inner = ", ".join(f"'{v}'" for v in escaped)
    return f"ARRAY[{inner}]"


def pg_str(value: str) -> str:
    """Escape a string for use in a SQL single-quoted literal."""
    return value.replace("'", "''")


def fetch_fonts() -> list[dict]:
    print(f"Fetching fonts from Google Fonts API...")
    req = urllib.request.Request(
        GOOGLE_FONTS_URL,
        headers={"User-Agent": "Mozilla/5.0 (compatible; font-migration-script/1.0)"},
    )
    with urllib.request.urlopen(req) as response:
        data = json.loads(response.read().decode())
    # gwfh returns a list directly; Google Fonts API returns {"items": [...]}
    fonts = data if isinstance(data, list) else data.get("items", [])
    print(f"  → {len(fonts)} fonts retrieved")
    return fonts


def build_migration(fonts: list[dict]) -> str:
    lines = []
    lines.append("-- Auto-generated by generate_fonts_migration.py")
    lines.append(f"-- Source: Google Fonts API  |  Generated: {datetime.utcnow().isoformat()}Z")
    lines.append(f"-- Total fonts: {len(fonts)}")
    lines.append("")
    lines.append("-- Upsert all Google Fonts into the fonts table.")
    lines.append("-- ON CONFLICT updates variants/subsets/category in case they changed.")
    lines.append("")

    # Process in batches so the file stays readable
    for batch_start in range(0, len(fonts), BATCH_SIZE):
        batch = fonts[batch_start: batch_start + BATCH_SIZE]
        lines.append("INSERT INTO fonts (name, category, variants, subsets, is_google_font) VALUES")

        row_lines = []
        for font in batch:
            # gwfh uses "family"; Google Fonts API uses "family" too but some use "name"
            name = pg_str(font.get("family", font.get("name", "")))
            category = pg_str(font.get("category", "sans-serif"))
            variants = font.get("variants", ["regular"])
            subsets = font.get("subsets", ["latin"])

            row_lines.append(
                f"  ('{name}', '{category}', {pg_array(variants)}, {pg_array(subsets)}, true)"
            )

        lines.append(",\n".join(row_lines))
        lines.append(
            "ON CONFLICT (name) DO UPDATE SET\n"
            "  category   = EXCLUDED.category,\n"
            "  variants   = EXCLUDED.variants,\n"
            "  subsets    = EXCLUDED.subsets,\n"
            "  is_google_font = true;\n"
        )

    return "\n".join(lines)


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    fonts = fetch_fonts()
    sql = build_migration(fonts)

    os.makedirs(MIGRATIONS_DIR, exist_ok=True)
    with open(MIGRATION_PATH, "w", encoding="utf-8") as f:
        f.write(sql)

    print(f"\n✅ Migration written to:\n   {MIGRATION_PATH}")
    print(f"   {len(fonts)} fonts  |  file size: {os.path.getsize(MIGRATION_PATH):,} bytes")
    print("\nApply it with:")
    print("   supabase db push")


if __name__ == "__main__":
    main()
