-- Revert: Remove incorrectly added job type categories from job_types table
DELETE FROM job_types WHERE name IN (
  'Residential Services',
  'Commercial Services',
  'Industrial Services',
  'Government & Municipal Services',
  'Construction & Contracting',
  'General Contracting',
  'Specialty Trades',
  'Infrastructure & Civil Works',
  'Preventative Maintenance',
  'Emergency Services',
  'Installation Services',
  'Assembly Services',
  'Electrical Services',
  'Plumbing Services',
  'HVAC & Mechanical',
  'Appliance Services',
  'Cleaning Services',
  'Janitorial Services',
  'Restoration & Remediation',
  'Waste Management',
  'Pest & Wildlife Control',
  'Landscaping & Outdoor Services',
  'Snow & Seasonal Services',
  'Pool & Water Systems',
  'Automotive Services',
  'Fleet Services',
  'Mobile Services',
  'Facility Management',
  'Property Management',
  'Real Estate Services',
  'Security Systems',
  'Fire & Safety Services',
  'Inspection Services',
  'Compliance & Auditing',
  'Energy Services',
  'Solar & Renewable Energy',
  'Utilities & Infrastructure',
  'Telecom Services',
  'IT & Networking',
  'Low Voltage Systems',
  'Healthcare Services',
  'Home Healthcare',
  'Personal Care Services',
  'Logistics Services',
  'Courier & Delivery',
  'Moving & Hauling',
  'Hospitality Services',
  'Event Services',
  'Retail Services',
  'Professional Services',
  'Manufacturing Services',
  'Industrial Maintenance',
  'Agriculture & Farming Services',
  'Marine & Coastal Services'
);
