-- Add original hardcoded industries from getIndustry function to industries table
INSERT INTO industries (name) VALUES
  ('Accounting'),
  ('Advertising & Marketing'),
  ('Aerospace & Defense'),
  ('Agriculture & Farming'),
  ('Architecture & Planning'),
  ('Automotive'),
  ('Banking & Financial Services'),
  ('Biotechnology'),
  ('Construction'),
  ('Consulting'),
  ('Consumer Electronics'),
  ('Consumer Goods'),
  ('E-commerce'),
  ('Education & Training'),
  ('Energy & Utilities'),
  ('Engineering'),
  ('Entertainment & Media'),
  ('Environmental Services'),
  ('Fashion & Apparel'),
  ('Food & Beverage'),
  ('Government & Public Sector'),
  ('Healthcare & Medical'),
  ('Hospitality & Tourism'),
  ('Human Resources'),
  ('Information Technology'),
  ('Insurance'),
  ('Legal Services'),
  ('Logistics & Supply Chain'),
  ('Manufacturing'),
  ('Mining & Metals'),
  ('Non-Profit & NGO'),
  ('Oil & Gas'),
  ('Pharmaceuticals'),
  ('Real Estate'),
  ('Retail'),
  ('Security Services'),
  ('Software Development'),
  ('Sports & Recreation'),
  ('Telecommunications'),
  ('Transportation'),
  ('Other')
ON CONFLICT (name) DO NOTHING;
